name: Translate Docs Weekly Task

on:
  schedule:
    - cron: "0 8 * * 1" # 8:00 every Monday
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Translate Docs
        run: |
          touch .env
          echo DEEPL_API_KEY=${{secrets.DEEPL_API_KEY}} >> .env
          echo GITHUB_TOKEN=${{secrets.GH_TOKEN}} >> .env
          yarn translate
          git add .
          git commit -m "Translate docs"
          git push -f origin master

      - name: Trigger milvus.io
        run: |
          curl -XPOST -H "Authorization: Bearer ${{secrets.GH_TOKEN}}" https://api.github.com/repos/milvus-io/milvus.io/dispatches -d '{"event_type": "prod-deploy"}'
